lead: >
  Російські поїзди плагіаризують іноземні винаходи, що відображає імперію, нездатну до справжньої творчості.
sources: >
  Youtube: [Про Україну!](https://www.youtube.com/@pro-ukrainu)

  - [Плагіат автомобілів у СРСР - скопіювали майже все!](https://youtu.be/gjjCI6TYtsg)
cases:
  - name: ІС20-16
    code: is20-16
    year: 1932
    link: https://uk.wikipedia.org/wiki/%D0%9F%D0%B0%D1%80%D0%BE%D0%B2%D0%BE%D0%B7_%D0%86%D0%A1
    origins:
      - name: Central Hudson Commodore Vanderbilt J-1e
        code: commodore
        year: 1931
        link: https://en.wikipedia.org/wiki/New_York_Central_Hudson
  - name: СРСР 2-3-2
    code: ussr-2-3-2
    year: 1938
    link: https://de.wikipedia.org/wiki/S%C5%BDD-Baureihe_2-3-2%D0%92
    origins:
      - name: Central Hudson J-3a
        code: new
        year: 1937
        link: https://en.wikipedia.org/wiki/New_York_Central_Hudson
