lead: >
  Os trens russos plagiam invenções estrangeiras, refletindo um império incapaz de verdadeira criatividade.
sources: >
  Youtube: [About Ukraine!](https://www.youtube.com/@pro-ukrainu)

  - [Cars plagiarisms in USSR](https://youtu.be/gjjCI6TYtsg)
cases:
  - name: IS20-16
    code: is20-16
    year: 1932
    link: https://en.wikipedia.org/wiki/Soviet_locomotive_class_IS
    origins:
      - name: Commodore Vanderbilt J-1e
        code: commodore
        year: 1931
        link: https://en.wikipedia.org/wiki/New_York_Central_Hudson
  - name: USSR 2-3-2
    code: ussr-2-3-2
    year: 1938
    link: https://de.wikipedia.org/wiki/S%C5%BDD-Baureihe_2-3-2%D0%92
    origins:
      - name: New York Central Hudson J-3a
        code: new
        year: 1937
        link: https://en.wikipedia.org/wiki/New_York_Central_Hudson
  - name: Yak-24
    code: yak-24
    year: 1955
    link: https://en.wikipedia.org/wiki/Yakovlev_Yak-24
    origins:
      - name: Piasecki HRP Rescuer
        code: piasecki
        year: 1945
        link: https://pt.wikipedia.org/wiki/Piasecki_HRP_Rescuer
  - name: Li-2
    code: li-2
    year: 1939
    link: https://pt.wikipedia.org/wiki/Lisunov_Li-2
    origins:
      - name: Douglas DC 3
        code: douglas
        year: 1936
        link: https://pt.wikipedia.org/wiki/Douglas_DC-3
  - name: Tu-4
    code: tu-4
    year: 1946
    link: https://en.wikipedia.org/wiki/Tupolev_Tu-4
    origins:
      - name: Boeing B-29 Superfortress
        code: boeing
        year: 1943
        link: https://pt.wikipedia.org/wiki/Boeing_B-29_Superfortress
  - name: Tu-144 «Concordski»
    code: tu-144
    year: 1968
    link: https://pt.wikipedia.org/wiki/Tupolev_Tu-144
    origins:
      - name: Concorde
        code: concorde
        year: 1968
        link: https://pt.wikipedia.org/wiki/Concorde
  - name: Buran
    code: buran
    year: 1984
    link: https://pt.wikipedia.org/wiki/Buran
    origins:
      - name: Columbia
        code: columbia
        year: 1981
        link: https://pt.wikipedia.org/wiki/Columbia_(%C3%B4nibus_espacial)
